### ISSUE TITLE
Remove windows packages with no vc feature

### ISSUE THREAD

**Issue by isuruf** [conda-forge/gsl-feedstock#17]
See, https://anaconda.org/conda-forge/gsl/files
This is probably because there is no features tracked for the python 3.6 build. (It should be skipped)

**Comment by ocefpaf** [comment]
@isuruf I think I got all.

**Comment by isuruf** [comment]
There's still https://anaconda.org/conda-forge/gsl/2.2.1/download/win-64/gsl-2.2.1-1.tar.bz2  and https://anaconda.org/conda-forge/gsl/2.2.1/download/win-64/gsl-2.2.1-0.tar.bz2

**Comment by ocefpaf** [comment]
Thanks. Now I think I got them all :grimacing:

**Comment by isuruf** [comment]
Yep. thanks

**Comment by ocefpaf** [comment]
Thank you for looking into this!
