### ISSUE TITLE
update version

### ISSUE THREAD

**Issue by dougalsutherland** [conda-forge/gsl-feedstock#22]
2.3 and 2.4 have been out for a while, but the huge patch used on Windows doesn't apply to the 2.4 sources anymore, and https://github.com/ampl/gsl/ hasn't updated it.

I might look into fixing it later, but not right now.

**Comment by jakirkham** [comment]
cc @shadowwalkersb

**Comment by dougalsutherland** [comment]
Oh, it looks like there is at least 2.3 support in that repo: https://github.com/ampl/gsl/tree/v2.3.0. Could generate a patch for 2.3 at least from that, I suppose.

https://www.gnu.org/software/gsl/extras/native_win_builds.html also suggests https://github.com/aweatherguy/GSL-on-Windows, which is a set of perl scripts to alter a source distribution of GSL to build on Windows, and might require less intervention for future versions. I don't think the build files it makes are compatible with VC9, though.

**Comment by ocefpaf** [comment]
@dougalsutherland I'd say let's go for the new versions and drop Windows for now. Just open an issue and someone with more Windows experience can try that later. No need to keep OS X and Linux users, who are a majority here, waiting on a patch :wink:

**Comment by dougalsutherland** [comment]
@ocefpaf I'll see if I can get the patch building for 2.3 first since it should actually be easy. Then we can do a Unix-only 2.4 after that.

**Comment by ocefpaf** [comment]
Awesome! Thanks @dougalsutherland!!

**Comment by jeromekelleher** [comment]
What about the [2.4 release](https://github.com/ampl/gsl/releases/tag/v2.4.0) in the https://github.com/ampl/gsl/ repo @dougalsutherland? I haven't tried it out, but was just wondering if you'd seen it.

**Comment by dougalsutherland** [comment]
Yep, that was new from https://github.com/ampl/gsl/issues/26#event-1503222372 -- I didn't see that apparently the work had actually been done. Will send a PR with that version tonight and see if it avoids the weird error of https://github.com/conda-forge/gsl-feedstock/pull/23#issuecomment-370230554.
