### ISSUE TITLE
Defaults GSL pulled in on gcc7 label

### ISSUE THREAD

**Issue by jeromekelleher** [conda-forge/gsl-feedstock#33]
I'm having trouble building a downstream package in which ``gsl`` is being pulled from the ``defaults`` channel rather than ``conda-forge``. I'm not sure why, but I think this must be an issue with the pinning for GSL.

The error is happening in [this PR](https://github.com/conda-forge/msprime-feedstock/pull/18), for the msprime-feedstock. This package compiles against both numpy and GSL, so perhaps is doing something that other packages aren't.

CI all passes except for the ``osx_c_compilerclang`` variants on Travis. The difference between these seems to be that in this case ``gsl`` is pulled from ``defaults`` instead of ``conda-forge``. I.e,
[here](https://travis-ci.org/conda-forge/msprime-feedstock/jobs/459348562#L574) is the failing example, and [here](https://travis-ci.org/conda-forge/msprime-feedstock/jobs/459348565#L542), [here](https://ci.appveyor.com/project/conda-forge/msprime-feedstock/builds/20534362/job/xybfpqo7mnc77897#L264) are examples where CI succeeds when we pull in GSL from conda-forge. However, on Linux we pull in from defaults [here](https://circleci.com/gh/conda-forge/msprime-feedstock/134) and CI also succeeds, so it seems that it doesn't matter that we're pulling this version on Linux.

It seems to me that we should always pull GSL from conda-forge though, and it's a bug if we sometimes pull from upstream instead??

**Comment by ocefpaf** [comment]
We are pinning to `gsl 2.2` and that one was probably not rebuild. We need to either update the pin or to build `2.2` for the new compilers.

**Comment by jeromekelleher** [comment]
> We are pinning to gsl 2.2 and that one was probably not rebuild. We need to either update the pin or to build 2.2 for the new compilers.

Makes sense. Anything I can help with?

**Comment by ocefpaf** [comment]
I re-pinned it here:

https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/154

But that means we will need to re-build (re-render) the packages that depends on `gsl`.

**Comment by jeromekelleher** [comment]
> But that means we will need to re-build (re-render) the packages that depends on gsl.

Great, thanks for the speedy action @ocefpaf! Will these rebuilds occur automatically through the bots or do we need to open PRs manually? (I'm happy to do some footwork here)

**Comment by CJ-Wright** [comment]
Yeah, you could create a one-off migrator for this if you wanted.

**Comment by ocefpaf** [comment]
> Yeah, you could create a one-off migrator for this if you wanted.

Want? Yes. Should we do it now while we juggle the compiler migration? Maybe not...

The long term goal would be a migrator that would start every time a PR bumping version in https://github.com/conda-forge/conda-forge-pinning-feedstock is merged 😬

**Comment by CJ-Wright** [comment]
xref: https://github.com/regro/cf-scripts/issues/44
