### ISSUE TITLE
Missing link fixing for openblas on OSX clang

### ISSUE THREAD

**Issue by jeromekelleher** [conda-forge/gsl-feedstock#34]
I'm having problems building a [downstream package](https://github.com/conda-forge/msprime-feedstock/pull/18) which depends on GSL, and I think it must be something to do with GSL packaging.

On the standard toolchain, we get lots of "Fixing linking of .." messages from conda build [here](https://travis-ci.org/conda-forge/msprime-feedstock/jobs/459904968#L504). This includes ``
libopenblas.dylib`` right after ``libgsl.23.dylib``.

However, on the ``osx_c_compilerclang`` toolchain, we seem to be missing a bunch of these ``Fixing linking of .." message from conda build [here](https://travis-ci.org/conda-forge/msprime-feedstock/jobs/459904966#L545). In particular, the linkage for openblas doesn't get fixed.

Later, the [build fails](https://travis-ci.org/conda-forge/msprime-feedstock/jobs/459904966#L611) 
because of a missing symbol ``_cblas_caxpy`` in GSL. 

Is this a known issue with conda build on OSX? Any pointers on how to track this down would be much appreciated;  unfortunately I don't have access to an OSX machine and know very little about its linking system quirks.

**Comment by duncanmmacleod** [comment]
@jeromekelleher, are able to to say whether #35 fixed your linking issue? It doesn't seem to have fixed mine.

**Comment by jeromekelleher** [comment]
Unfortunately not @duncanmmacleod, I'm still getting [linking problems](https://travis-ci.org/conda-forge/msprime-feedstock/jobs/459904964#L659) against blas. Are you having similar issues?

**Comment by duncanmmacleod** [comment]
@jeromekelleher, aye, it looks basically the same problem as yours [[link](https://travis-ci.org/conda-forge/lal-feedstock/jobs/463340679)].

**Comment by jeromekelleher** [comment]
Yeah, looks like the same thing. It seems to me that it's the missing 'fixing linking' steps that are the issue, but I've no idea how to dig into this. Possibly an upstream bug in conda build? 

I've been scratching my head a lot on this one, and I'd really appreciate any thoughts you might have.

**Comment by duncanmmacleod** [comment]
Maybe @conda-forge/core might be able to help?

**Comment by duncanmmacleod** [comment]
Help me @conda-forge/core,@conda-forge/help-c-cpp, you're my only hope.

**Comment by scopatz** [comment]
Can you please post the actual error?

**Comment by duncanmmacleod** [comment]
@scopatz, the problem is that on the `osx_c_compilerclang` builds, downstream packages are failing to resolve `cblas` symbols. See [this failure](https://travis-ci.org/conda-forge/msprime-feedstock/jobs/459904966#L611) (@jeromekelleher):

```pytb
Traceback (most recent call last):
import: 'msprime'
  File "/Users/travis/miniconda3/conda-bld/msprime_1544721774492/test_tmp/run_test.py", line 2, in <module>
    import msprime
  File "/Users/travis/miniconda3/conda-bld/msprime_1544721774492/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.7/site-packages/msprime/__init__.py", line 26, in <module>
    from _msprime import FORWARD  # NOQA
ImportError: dlopen(/Users/travis/miniconda3/conda-bld/msprime_1544721774492/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.7/site-packages/_msprime.cpython-37m-darwin.so, 2): Symbol not found: _cblas_caxpy
  Referenced from: /Users/travis/miniconda3/conda-bld/msprime_1544721774492/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libgsl.23.dylib
  Expected in: flat namespace
 in /Users/travis/miniconda3/conda-bld/msprime_1544721774492/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libgsl.23.dylib
```

or [this one](https://travis-ci.org/conda-forge/lal-feedstock/jobs/463340679):

```
dyld: lazy symbol binding failed: Symbol not found: _cblas_dasum
  Referenced from: $PREFIX/lib/libgsl.23.dylib
  Expected in: flat namespace
```

**Comment by isuruf** [comment]
This is an issue with the linker stripping the blas library due to the flag `-Wl,-dead-strip-dylibs` in `osx_c_compilerclang` builds. There are 2 options here,

1. Remove `-Wl,-dead-strip-dylibs` from LDFLAGS in all downstream packages linking to gsl with this problem.
2. Build gsl by doing `LIBS=-lcblas` before running configure so that the weak linking is removed. This is fine as we require openblas in this recipe.

**Comment by jeromekelleher** [comment]
Thanks @isuruf! The second option seems like the simpler to me, since it involves changing only GSL.

**Comment by duncanmmacleod** [comment]
Seconded, thanks @isuruf!

**Comment by jeromekelleher** [comment]
If there's something I can do to help here @isuruf, please let me know. I don't really know where to start with changing the GSL build, unfortunately.

**Comment by beckermr** [comment]
I have hit this error too. Can we merge #37 @isuruf?
