### ISSUE TITLE
Missing header gsl/gsl_rng.h

### ISSUE THREAD

**Issue by mmb90** [conda-forge/gsl-feedstock#4]
The exact error is 
```In file included from pypolyagamma/cpp/include/RNG.hpp:33:0, from pypolyagamma/pypolyagamma.cpp:326: pypolyagamma/cpp/include/GRNG.hpp:32:25: fatal error: gsl/gsl_rng.h: No such file or directory #include <gsl/gsl_rng.h> ^ compilation terminated. error: command 'gcc' failed with exit status 1```
I'm trying to add my [package](https://github.com/Savvysherpa/pypolyagamma) to [conda-forge](https://github.com/conda-forge/staged-recipes/pull/831) and I get this error when CircleCI is running.

**Comment by ocefpaf** [comment]
The file exists and I believe you need to tell you package to look for it in `$PREFIX/include` instead.
