### ISSUE TITLE
Invalid symlinks in Linux packages

### ISSUE THREAD

**Issue by dpryan79** [conda-forge/gsl-feedstock#56]
At least on linux, using gsl-2.6-he838d99_2, there are some symlinks that go no where:

```
$ ls -l lib
total 11648
-rw-r--r-- 1 dryan dryan 7019094 Jan 15 21:30 libgsl.a
lrwxrwxrwx 1 dryan dryan      16 Jan 15 21:30 libgsl.so -> libgsl.so.25.0.0
lrwxrwxrwx 1 dryan dryan      16 Jan 15 21:30 libgsl.so.25 -> libgsl.so.25.0.0
-rwxr-xr-x 1 dryan dryan 3465328 Jan 15 21:30 libgsl.so.25.0.0
-rw-r--r-- 1 dryan dryan  614610 Jan 15 21:30 libgslcblas.a
lrwxrwxrwx 1 dryan dryan      13 Jan 15 21:30 libgslcblas.so -> libcblas.so.3           # problem
lrwxrwxrwx 1 dryan dryan      13 Jan 15 21:30 libgslcblas.so.0 -> libcblas.so.3         # problem
-rwxr-xr-x 1 dryan dryan  366136 Jan 15 21:30 libgslcblas.so.0.0.0
drwxr-xr-x 1 dryan dryan     512 Feb 19 15:50 pkgconfig
```

`libcblas.so.3` doesn't exist and presumably the links to it should have been `libgslcblas.so.0.0.0` instead.

**Comment by traversaro** [comment]
I guess this is related to the code block in https://github.com/conda-forge/gsl-feedstock/blob/d46961ab0785c7a46fe1661d3592edbf64fcbca0/recipe/build.sh#L74 , I am not sure why it is there.

**Comment by traversaro** [comment]
Probably it was removed in https://github.com/conda-forge/gsl-feedstock/pull/43/files as it was a symlink, but now the gsl build system probably adds more symlinks.

**Comment by dpryan79** [comment]
We think we figured it out. When the package is installed into an environment conda seems to handle this properly.
